---
version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: title
        must_include:
          regex: \[[Major|Minor|Patch|NoVersion]\]
          message: 'Please include semver tag in the title, see https://semver.org/ for more info.'
      - do: description
        must_exclude:
          regex: \[ \] Have you tested your changes with 100% coverage
          message: 'Please complete testing before merging.'
